require 'colorize' 


puts "                              ......?ZOOOO7.. ....".colorize( :blue )                              
puts "                        ...ZO..OOOZZZZOOOOOOZZOO..?Z....".colorize( :blue )                        
puts "                    ...OOO..OZZO..    ..      .$OZZ7.ZOO....".colorize( :blue )                   
puts "                ...ZOZO..OZO..  ..  ...O....  ..  .OOZ..ZZOO....".colorize( :blue )               
puts "                .ZZOZO.ZOO....  ..  ..ZOO...  ..  ...OZZ..ZOOZZ.".colorize( :blue )               
puts "            ..ZZZOOO..OO..    ..OZ..  O.O.  .ZO...  ...ZZ+.OOOOOO...".colorize( :blue )            
puts "          ..ZZOOOOO.ZOO....O.... .I.    ..  ...,...O.....ZO.ZOOOOOO=..".colorize( :blue )          
puts "        ..ZOOOOOOZ.ZZ.  ..OZO.                    7OO.....OO.7OOOOOOO:..".colorize( :blue )        
puts "      ..ZOOOOOOOZ.OO..    O.O.                    Z.,.    .OZ.OZOOOOOOO...".colorize( :blue )      
puts "      ZOZOOOOOOO.+Z...    ....                    ....    ..ZO.ZOOOOOOOOO.".colorize( :blue )      
puts "    .OOOOOOOOOZ..OZ..".colorize( :blue )+"$$$$$...Z$$$$$,$$$$$$$$$$$$$$$$$".colorize( :red )+".      OO..ZZOOOOOOZOO.".colorize( :blue )    
puts "  .OZZOOOOOOOOO ZZ....".colorize( :blue )+"$Z$$Z..,$Z$$..IZ$$$$$$$$.$$$$$".colorize( :red )+"..      .OZ.OOOOOOOOOOZZ..".colorize( :blue )  
puts "..OOOOOOOOOOOO..OZ..  .".colorize( :blue )+"$$$$$...$$$   $$$+.  .$$.$$$$".colorize( :red )+"..      .ZZ..ZOOOOOOOOOOO...".colorize( :blue )
puts ".ZOOOOOOOOOOOO..O~    .".colorize( :blue )+"$$$$$...$$$   $$$+.  ..  $$$$".colorize( :red )+"..        Z..OOOOOOOOOOOOO..".colorize( :blue )
puts ".OOOOOOOOOOOOO..O.    .".colorize( :blue )+"$$$$$$..$$$   $$$+.  $$  $$$$".colorize( :red )+"..        ZO.OOOOOOOOOOOOO..".colorize( :blue )
puts "...............OO.    .".colorize( :blue )+"$$$$$$$.$$$   $$$+...Z$  $$$$".colorize( :red )+"..        OO................".colorize( :blue )
puts ".$$$$$$$$$$$$$.?Z.    .".colorize( :blue )+"$$$$Z$$.$$$   $$$$$$$$$  $$$$".colorize( :red )+"......    OO.$$$$$$$$$$$$$..".colorize( :blue )
puts ".$$$$$$$$$$$$$ .O.    .".colorize( :blue )+"$$$.$$$$$$$   $$$I.  Z$  $$$$$Z$$Z".colorize( :red )+"...  ZZ.$$$$$$$$$$$$$..".colorize( :blue )
puts ".:$$$$$$$$$$$$..OZ    .".colorize( :blue )+"$$$..$$$$$$   $$$I.  .$  $$$$$$$$$$".colorize( :red )+"..  O..$$$$$$$$$$$$$..".colorize( :blue )
puts "  .$$$$$$$$$$$$.OO..  .".colorize( :blue )+"$$$. $$$$$$   $$$I   ..  $$$$.$$ZZ$".colorize( :red )+"...ZO.,$$$$$$$$$$$..".colorize( :blue )  
puts "  ..Z$$$$$$$$$$..Z..  .".colorize( :blue )+"$$$. .$$$$$   $$$I       $$$$..  Z$".colorize( :red )+"...OZ.$$$$$$$$$$Z...".colorize( :blue )  
puts "    .$$$$$$$$$$$.OZ..".colorize( :blue )+"$$$$$...$ZZ$$   $$$I       ZZ$$...Z$$".colorize( :red )+"..OO.=$$$$$$$$Z$..".colorize( :blue )    
puts "      .$$$$$$$$$..OO..".colorize( :blue )+"$$$$..  $$$$   $$$I     .IZ$$$$$$$$".colorize( :red )+"..OZ..$$$$$$$$$..".colorize( :blue )      
puts "      ...$$$$$$$$..OO...".colorize( :blue )+"$Z$.  .$$$   $$$I     Z$$$$$$$$$".colorize( :red )+"..OZ..Z$$$$$$$...".colorize( :blue )       
puts "        ...$$$$$$Z..OO......  ".colorize( :blue )+"....  $Z$$$.".colorize( :red )+"    ..... .....OZ..$$$$$$$....".colorize( :blue )       
puts "            .$ZZ$$Z..OZ...          ".colorize( :blue )+"...$$.".colorize( :red )+"            ..ZZ..$$$$$$..".colorize( :blue )           
puts "             .Z$$$$$.OZZ...            ".colorize( :blue )+"..".colorize( :red )+"          ..OZO.$$$$$Z..".colorize( :blue )              
puts "                Z$$$:.OZZ. ...                ....OOO..$$$$." .colorize( :blue )                 
puts "               ...$$$$.OZZZ..                .OOOO.=$$$....".colorize( :blue )                  
puts "                     ...$Z..OZOZO....    ...OZOZO .$$....".colorize( :blue )                      
puts "                         ...~$..OZOOZOOOOOZZO..=$...".colorize( :blue )    