puts "                              ......?ZOOOO7.. ...."                              
puts "                        ...ZO..OOOZZZZOOOOOOZZOO..?Z...."                        
puts "                    ...OOO..OZZO..    ..      .$OZZ7.ZOO...."                    
puts "                ...ZOZO..OZO..  ..  ...O....  ..  .OOZ..ZZOO...."               
puts "                .ZZOZO.ZOO....  ..  ..ZOO...  ..  ...OZZ..ZOOZZ."                
puts "            ..ZZZOOO..OO..    ..OZ..  O.O.  .ZO...  ...ZZ+.OOOOOO..."            
puts "          ..ZZOOOOO.ZOO....O.... .I.    ..  ...,...O.....ZO.ZOOOOOO=.."          
puts "        ..ZOOOOOOZ.ZZ.  ..OZO.                    7OO.....OO.7OOOOOOO:.."        
puts "      ..ZOOOOOOOZ.OO..    O.O.                    Z.,.    .OZ.OZOOOOOOO..."      
puts "      ZOZOOOOOOO.+Z...    ....                    ....    ..ZO.ZOOOOOOOOO."      
puts "    .OOOOOOOOOZ..OZ..$$$$$...Z$$$$$,$$$$$$$$$$$$$$$$$.      OO..ZZOOOOOOZOO."    
puts "  .OZZOOOOOOOOO ZZ....$Z$$Z..,$Z$$..IZ$$$$$$$$.$$$$$..      .OZ.OOOOOOOOOOZZ.."  
puts "..OOOOOOOOOOOO..OZ..  .$$$$$...$$$   $$$+.  .$$.$$$$..      .ZZ..ZOOOOOOOOOOO..."
puts ".ZOOOOOOOOOOOO..O~    .$$$$$...$$$   $$$+.  ..  $$$$..        Z..OOOOOOOOOOOOO.."
puts ".OOOOOOOOOOOOO..O.    .$$$$$$..$$$   $$$+.  $$  $$$$..        ZO.OOOOOOOOOOOOO.."
puts "...............OO.    .$$$$$$$.$$$   $$$+...Z$  $$$$..        OO................"
puts ".$$$$$$$$$$$$$.?Z.    .$$$$Z$$.$$$   $$$$$$$$$  $$$$......    OO.$$$$$$$$$$$$$.."
puts ".$$$$$$$$$$$$$ .O.    .$$$.$$$$$$$   $$$I.  Z$  $$$$$Z$$Z...  ZZ.$$$$$$$$$$$$$.."
puts ".:$$$$$$$$$$$$..OZ    .$$$..$$$$$$   $$$I.  .$  $$$$$$$$$$..  O..$$$$$$$$$$$$$.."
puts "  .$$$$$$$$$$$$.OO..  .$$$. $$$$$$   $$$I   ..  $$$$.$$ZZ$...ZO.,$$$$$$$$$$$.."  
puts "  ..Z$$$$$$$$$$..Z..  .$$$. .$$$$$   $$$I       $$$$..  Z$...OZ.$$$$$$$$$$Z..."  
puts "    .$$$$$$$$$$$.OZ..$$$$$...$ZZ$$   $$$I       ZZ$$...Z$$..OO.=$$$$$$$$Z$.."    
puts "      .$$$$$$$$$..OO..$$$$..  $$$$   $$$I     .IZ$$$$$$$$..OZ..$$$$$$$$$.."      
puts "      ...$$$$$$$$..OO...$Z$.  .$$$   $$$I     Z$$$$$$$$$..OZ..Z$$$$$$$..."       
puts "        ...$$$$$$Z..OO......  ....  $Z$$$.    ..... .....OZ..$$$$$$$...."       
puts "            .$ZZ$$Z..OZ...          ...$$.            ..ZZ..$$$$$$.."           
puts "             .Z$$$$$.OZZ...            ..          ..OZO.$$$$$Z.."              
puts "                Z$$$:.OZZ. ...                ....OOO..$$$$."                  
puts "               ...$$$$.OZZZ..                .OOOO.=$$$...."                  
puts "                     ...$Z..OZOZO....    ...OZOZO .$$...."                      
puts "                         ...~$..OZOOZOOOOOZZO..=$..."    